### ISSUE TITLE
Deprecated selector in `norminette-linter\styles\norminette-linter.less`

### ISSUE THREAD

**Issue by aeliusrs** [Kerosene2000/atom-norminette-linter#12]
In `norminette-linter\styles\norminette-linter.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-highlight.norm,
.linter-highlight.norm` => `atom-text-editor.editor .linter-highlight.norm,
.linter-highlight.norm`

* `atom-text-editor::shadow .linter-highlight.norm:not(.line-number),
.linter-highlight.norm:not(.line-number)` => `atom-text-editor.editor .linter-highlight.norm:not(.line-number),
.linter-highlight.norm:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.norm .linter-gutter,
.linter-highlight.norm .linter-gutter` => `atom-text-editor.editor .linter-highlight.norm .linter-gutter,
.linter-highlight.norm .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.norm .region,
.linter-highlight.norm .region` => `atom-text-editor.editor .linter-highlight.norm .region,
.linter-highlight.norm .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by aeliusrs** [comment]
Svp Corriger le au Plus vite :D 💃

**Comment by Kerollmops** [comment]
Last update (v0.3.1) fixes this deprecate error, can you check that, plz ?

**Comment by aeliusrs** [comment]
Oh nice !!! Thank you a lot !! 

But now i've another small issue, maybe you can lead me to the good way to fix this, when i save and so run the norminette i got this in my console : 

linter-registry.js:144 [Linter] Error running norminette TypeError: Cannot convert undefined or null to object(…)

**Comment by aeliusrs** [comment]
just close
