### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wixa** [Kerosene2000/atom-norminette-linter#13]
Can anybody help me? I install norminette, but have a trable: 
![screen shot 2017-09-02 at 3 58 37 pm](https://user-images.githubusercontent.com/10008298/29995674-ab52b5cc-8ff7-11e7-93b8-d92d0282b1eb.png)

**Comment by Kerollmops** [comment]
This is a norminette error not from my extension.
It means the norminette cannot establish a connection with a server.
Ask the bocal for that...

**Comment by wixa** [comment]
Thank you
