### ISSUE TITLE
Erreur : ruby ne trouve pas le fichier

### ISSUE THREAD

**Issue by Samuelfaure** [Kerosene2000/atom-norminette-linter#6]
Bonjour

Je n'arrive pas a configurer correctement le package : il semblerait qu'un fichier manque, probablement celui de la norminette ?

Celui-ci se trouve dans mon /bin/ sous le nom de "norminette"
Comment dois je modifier ma configuration pour que cela fonctionne ?

**Comment by Kerollmops** [comment]
si c'est une erreur ruby alors le probleme ne vient pas de ce plugin (tout est en coffeescript ici), essais de donner l'erreur sur le slack de 42 (42born2code.slack.com #norminette)
